version: "3.8"

services:
  api-service:
    build:
      context: ./api-service
    ports:
      - "5001:5000"

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "5002:5002"

  frontend:
    build:
      context: ./world-app
    ports:
      - "4200:80"
    depends_on:
      - api-service
      - auth-service